- name: Vercel
  logo: vercel
  url: https://vercel.com
  color: 111111
  logoColor: ffffff
  projects:
    - https://github.com/jasonappah/router
    - https://github.com/jasonappah/scrapbook-customizer
    - https://github.com/jasonappah/google-sheet-to-json

- name: Python
  logo: python
  url: https://python.org
  color: 3776ab
  logoColor: ffffff
  projects: 
    - https://github.com/jasonappah/subsplashuploader
    - url: https://github.com/jasonappah/tf-virtual-bg
      wip: true
    - url: https://github.com/jasonappah/stay-accountable
      wip: true

- name: Node.js
  logo: node.js
  url: https://nodejs.org
  color: 339933
  logoColor: ffffff
  projects: 
    - url: https://github.com/jasonappah/lt
      wip: true
