- name: Vercel
  logo: vercel
  url: https://vercel.com
  color: 111111
  projects:
    - url: https://github.com/jasonappah/router
    - url: https://github.com/jasonappah/scrapbook-customizer
    - url: https://github.com/jasonappah/google-sheet-to-json
    - url: https://github.com/jasonappah/api

- name: Python
  logo: python
  url: https://python.org
  color: 3776ab
  projects: 
    - url: https://github.com/jasonappah/subsplashuploader
    - url: https://github.com/jasonappah/tf-virtual-bg
      wip: true
    - url: https://github.com/jasonappah/stay-accountable
      wip: true

- name: Node.js
  logo: node.js
  url: https://nodejs.org
  color: 339933
  projects: 
    - url: https://github.com/jasonappah/lt
      wip: true
    - url: https://github.com/jasonappah/ewelink-plug

- name: Firebase
  logo: firebase
  url: https://firebase.google.com/
  color: ffca28
  logoColor: "000000"
  projects: 
    - url: https://github.com/jasonappah/ontime
      wip: true
    - url: https://github.com/jasonappah/store
      wip: true
    - url: https://github.com/jasonappah/shuttle
      wip: true

- name: FIRST
  logo: first
  color: 0066b3
  url: https://bit.ly/grizzlybots
  logoColor: "ffffff"
  projects: 
    - url: https://github.com/grizzlybots11918/ModernRoboticsCMCTest
    - url: https://github.com/grizzlybots11918/ultimategoal
      wip: true
      
- name: Next.js
  logo: next.js
  url: https://nextjs.org
  color: 111111
  projects:
  - url: https://github.com/jasonappah/wordcounter
  - url: https://github.com/grizzlybots11918/builds
  
  
